[pytest]
testpaths = tests
addopts = -v --cov=src --cov-report=html --cov-report=term-missing

[coverage:report]
exclude_lines =
    pragma: no cover
    if __name__ ==
    while True
    input(
    break

[report]
exclude_lines =
    pragma: no cover
    if __name__ ==
    while True
    input